import { useEffect, useState } from "react";
import { get, post } from "../../utils/api";

export default function SchoolDirectoryManager() {
  const [summary, setSummary] = useState(null); const [students, setStudents] = useState([]); const [personnelRecords, setPersonnelRecords] = useState([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [reissuing, setReissuing] = useState("");
  useEffect(() => { Promise.all([get("/api/admin/directory/summary"), get("/api/admin/directory/students"), get("/api/admin/directory/personnel")]).then(([nextSummary, nextStudents, nextPersonnel]) => { setSummary(nextSummary); setStudents(nextStudents.students || []); setPersonnelRecords(nextPersonnel.personnel || []); }).catch(() => setError("Unable to load the private school directory.")); }, []);
  const reissueActivation = async (identityId) => { setReissuing(identityId); setMessage(""); try { const response = await post(`/api/admin/directory/${identityId}/reissue-activation`, {}); setMessage(response.message || "Activation link sent."); } catch (nextError) { setMessage(nextError?.body?.error || "Unable to reissue the activation link."); } finally { setReissuing(""); } };
  if (error) return <p style={{ color: "#b91c1c" }}>{error}</p>;
  if (!summary) return <p>Loading school directory…</p>;
  const personnel = ["teacher", "staff", "admin", "superadmin"].map((role) => ({ role, count: summary.personnel?.[role] || 0 }));
  return <section style={{ maxWidth: 1120 }}>
    <h2>School Directory & Enrolment</h2><p style={{ color: "#475569" }}>Private school totals are calculated from verified active directory records. A student’s class and stream are the source of truth for results distribution and account activation.</p>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 12, margin: "18px 0" }}>
      <article style={{ background: "#ecfdf5", borderRadius: 8, padding: 16 }}><strong>{summary.wholeSchool.activeStudents}</strong><br />Active students</article>
      <article style={{ background: "#eff6ff", borderRadius: 8, padding: 16 }}><strong>{summary.wholeSchool.totalPersonnel}</strong><br />Active personnel</article>
      <article style={{ background: "#fefce8", borderRadius: 8, padding: 16 }}><strong>{summary.accountStates?.active || 0}</strong><br />Activated student accounts</article>
      <article style={{ background: "#fff7ed", borderRadius: 8, padding: 16 }}><strong>{summary.accountStates?.pre_registered || 0}</strong><br />Awaiting activation</article>
    </div>
    <h3>Students by class and stream</h3><table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 22 }}><thead><tr><th>Class</th><th>Stream</th><th>Students</th><th>Activated accounts</th></tr></thead><tbody>{summary.byClassAndStream.map((item) => <tr key={`${item.class}-${item.stream}`}><td>{item.class}</td><td>{item.stream}</td><td>{item.students}</td><td>{item.activatedAccounts}</td></tr>)}</tbody></table>
    <h3>Students by curriculum and grade/form</h3><table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 22 }}><thead><tr><th>Curriculum</th><th>Grade / form</th><th>Students</th></tr></thead><tbody>{summary.byCurriculum.map((item) => <tr key={`${item.curriculum}-${item.gradeOrForm}`}><td>{item.curriculum}</td><td>{item.gradeOrForm}</td><td>{item.students}</td></tr>)}</tbody></table>
    <h3>Personnel totals</h3><table style={{ width: "100%", borderCollapse: "collapse", marginBottom: 22 }}><thead><tr><th>Role</th><th>Active accounts</th></tr></thead><tbody>{personnel.map((item) => <tr key={item.role}><td>{item.role}</td><td>{item.count}</td></tr>)}</tbody></table>
    {message && <p style={{ color: message.includes("Unable") ? "#b91c1c" : "#166534" }}>{message}</p>}
    <h3>Verified personnel directory</h3><div style={{ overflowX: "auto", maxHeight: 320, marginBottom: 22 }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th>Name</th><th>Role</th><th>Staff ID</th><th>Department / position</th><th>Account status</th><th>Activation</th></tr></thead><tbody>{personnelRecords.map((person) => <tr key={person._id}><td>{person.name}</td><td>{person.role}</td><td>{person.staffId || "—"}</td><td>{person.department || person.position || "—"}</td><td>{person.accountStatus}</td><td>{["pre_registered", "invited"].includes(person.accountStatus) && <button type="button" onClick={() => reissueActivation(person._id)} disabled={reissuing === person._id}>Reissue link</button>}</td></tr>)}</tbody></table></div>
    <h3>Verified student directory</h3><div style={{ overflowX: "auto", maxHeight: 420 }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th>Admission no.</th><th>Name</th><th>Class</th><th>Stream</th><th>Curriculum</th><th>Account status</th><th>Activation</th></tr></thead><tbody>{students.map((student) => <tr key={student._id}><td>{student.admissionNumber}</td><td>{student.firstName} {student.lastName}</td><td>{student.class}</td><td>{student.stream}</td><td>{student.curriculum || "Not set"}</td><td>{student.accountStatus}</td><td>{["pre_registered", "invited"].includes(student.accountStatus) && <button type="button" onClick={() => reissueActivation(student._id)} disabled={reissuing === student._id}>Reissue link</button>}</td></tr>)}</tbody></table></div>
  </section>;
}
