import { useState } from "react";
import { get, post, upload } from "../../utils/api";

export default function TimetableImportManager() {
  const [file, setFile] = useState(null); const [preview, setPreview] = useState(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const downloadTemplate = async () => { try { const response = await fetch("/api/admin/timetables/template", { headers: { Authorization: `Bearer ${localStorage.getItem("token") || sessionStorage.getItem("token") || ""}` } }); if (!response.ok) throw new Error(); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "kangaru-timetable-template.xlsx"; anchor.click(); URL.revokeObjectURL(url); } catch { setMessage("Unable to download the timetable template."); } };
  const previewImport = async () => { if (!file) return setMessage("Choose one .xlsx timetable file."); const form = new FormData(); form.append("file", file); setBusy(true); setMessage(""); try { const response = await upload("/api/admin/timetables/preview", form); setPreview(response.import); } catch (error) { setMessage(error?.body?.error || "Unable to validate the timetable file."); } finally { setBusy(false); } };
  const confirm = async () => { if (!preview || preview.summary.invalidRows) return; setBusy(true); try { const result = await post(`/api/admin/timetables/${preview.id}/confirm`, {}); setMessage(`Distributed ${result.appliedRows} entries across ${result.distributedTimetables} class/stream timetable(s).`); setPreview(null); setFile(null); } catch (error) { setMessage(error?.body?.error || "Unable to distribute the timetable."); } finally { setBusy(false); } };
  return <section style={{ background: "#fff", border: "1px solid #dbeafe", borderRadius: 12, padding: 22 }}><h2 style={{ marginTop: 0 }}>Class & Stream Timetables</h2><p style={{ color: "#475569", lineHeight: 1.6 }}>Upload one Excel file to distribute timetable entries to the matching teacher and the students in each verified class and stream. Every row is validated before anything is published.</p><div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 14 }}><button type="button" onClick={downloadTemplate}>Download Excel template</button><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event) => setFile(event.target.files?.[0] || null)} /><button type="button" disabled={busy} onClick={previewImport}>{busy ? "Validating…" : "Validate timetable"}</button></div>{message && <p style={{ color: message.includes("Unable") ? "#b91c1c" : "#166534" }}>{message}</p>}{preview && <div style={{ marginTop: 18 }}><p><strong>{preview.summary.validRows}</strong> valid of {preview.summary.totalRows} entries. <strong>{preview.summary.invalidRows}</strong> invalid.</p><div style={{ overflowX: "auto", maxHeight: 320 }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th>Row</th><th>Class / stream</th><th>Teacher</th><th>Subject</th><th>Errors</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.data.class} / {row.data.stream}</td><td>{row.data.teacherStaffId}</td><td>{row.data.subject}</td><td style={{ color: row.errors?.length ? "#b91c1c" : "#166534" }}>{row.errors?.join("; ") || "Ready"}</td></tr>)}</tbody></table></div><button type="button" disabled={busy || preview.summary.invalidRows > 0} onClick={confirm} style={{ marginTop: 14, padding: "10px 16px", background: preview.summary.invalidRows ? "#94a3b8" : "#166534", color: "white", border: 0, borderRadius: 8 }}>Confirm and distribute</button></div>}</section>;
}
