import { useEffect, useState } from "react";
import { get, upload } from "../utils/api";

export default function TeacherWordPaperPanel({ exam, onClose, onUpdated }) {
  const [file, setFile] = useState(null); const [mediaReferences, setMediaReferences] = useState(""); const [paper, setPaper] = useState(null); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { get(`/api/exam-papers/${exam._id}`).then((data) => setPaper(data.paper)).catch(() => setPaper(null)); }, [exam._id]);
  const submit = async (event) => {
    event.preventDefault(); if (!file) return setStatus("Choose a DOCX exam paper first.");
    let references = []; try { references = mediaReferences.trim() ? JSON.parse(mediaReferences) : []; } catch { return setStatus("Media references must be a JSON array of secure HTTPS links."); }
    const formData = new FormData(); formData.append("paper", file); formData.append("mediaReferences", JSON.stringify(references)); setBusy(true); setStatus("");
    try { const response = await upload(`/api/exam-papers/${exam._id}`, formData); setPaper(response.paper); setFile(null); setStatus(`Paper version ${response.paper.version} is ready. It becomes immutable when the first student session starts.`); onUpdated?.(); } catch (error) { setStatus(error?.body?.error || "Unable to prepare the Word paper."); } finally { setBusy(false); }
  };
  return <section style={{ position: "fixed", inset: 0, background: "rgba(15,23,42,.6)", display: "grid", placeItems: "center", padding: 20, zIndex: 50 }}><div style={{ width: "min(700px,100%)", maxHeight: "90vh", overflow: "auto", background: "white", borderRadius: 12, padding: 24 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 16 }}><div><h2 style={{ margin: 0 }}>Word exam paper: {exam.title}</h2><p style={{ color: "#475569" }}>Students receive a rendered, read-only paper. They cannot edit the questions.</p></div><button type="button" onClick={onClose}>Close</button></div>{paper && <p style={{ padding: 10, background: "#ecfdf5", color: "#166534" }}>Current paper: version {paper.version} · {paper.sourceName}{paper.frozenAt ? " · frozen for student sessions" : " · editable until the first student starts"}</p>}<form onSubmit={submit}><label style={{ display: "grid", gap: 8, marginTop: 12 }}>DOCX question paper<input type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><label style={{ display: "grid", gap: 8, marginTop: 12 }}>Approved media references (optional JSON array)<textarea rows={4} value={mediaReferences} onChange={(event) => setMediaReferences(event.target.value)} placeholder={'[{"label":"Listening clip","url":"https://…","type":"audio"}]'} /></label><p style={{ fontSize: 13, color: "#475569" }}>Upload images, audio, video, or supporting resources through the existing resource upload first, then use their secure HTTPS links here. Only approved HTTPS links are accepted.</p><button type="submit" disabled={busy} style={{ padding: "10px 16px", background: "#2563eb", color: "white", border: 0, borderRadius: 8 }}>{busy ? "Preparing paper…" : "Create next paper version"}</button></form>{status && <p style={{ marginTop: 14, color: status.includes("ready") ? "#166534" : "#b91c1c" }}>{status}</p>}</div></section>;
}
